### ISSUE TITLE
AC bot test

### ISSUE THREAD

**Issue by Berkmann18** [marekrozmus/all-contributors-test#3]
@all-contributors Please add @marekrozmus for docs.

**Comment by marekrozmus** [comment]
@Berkmann18 What were you testing here? Do you need any more information?

**Comment by Berkmann18** [comment]
I was trying to get the bot to update the table after you raised https://github.com/all-contributors/all-contributors/issues/304.

**Comment by marekrozmus** [comment]
@all-contributors Please add @marekrozmus for docs

**Comment by marekrozmus** [comment]
@Berkmann18 seems to work, maybe the '.' at the end of your command was the problem. Sorry for late answer but somehow GitHub does not send me email about updates although I have subcription check.

**Comment by Berkmann18** [comment]
Yeah, good point.
